### ISSUE TITLE
Incremental Model interval_unit > cron

### ISSUE THREAD

**Issue by cmvarmour** [TobikoData/sqlmesh#1464]
We'd like to batch updates to a daily model every 15 minutes, but I think we are limited currently to `interval_unit < cron period`

I put together this example

# Model Definition
```
MODEL (
  name sqlmesh_example.incremental_model,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column ds
  ),
  start '2020-09-01',
  interval_unit 'day',
  cron '*/15 * * * *',
  grain ARRAY[id, ds]
);
```

# Error Message
```
Interval unit of 'IntervalUnit.DAY' is larger than cron period of '*/5 * * * *' at '/sqlmesh/vaweb/models/incremental_model.sql'
```

**Comment by tobymao** [comment]
cc @izeigerman

**Comment by izeigerman** [comment]
Interval Unit in SQLMesh is a measure of data completeness for your model. 

In other words, when you set the interval unit to `hour`, SQLMesh ensures that data for hour X will only be processed when that hour is over. Therefore if hour X is still ongoing, the model will not run for that X. Only at timestamp >= X + 1 the hour X can be processed.

When you set cron to `*/15 * * * *` with the intent to execute your model every 15 minutes, you expect it to run at X:15, X:30 and X:45. Though since the interval unit is set to `hourly`, SQLMesh concludes that hour X can't be processed at these timestamps since the data for this hour is still incomplete. Only starting at X + 1:00 can hour X be processed.

Since such configuration doesn't make sense from SQLMesh's perspective it raises an error.
