### ISSUE TITLE
Databricks Unity Catalog - Limit Permissions on Physical Schema

### ISSUE THREAD

**Issue by PtrckGdwn** [TobikoData/sqlmesh#1616]
Hi,

I am investigating the use of SQLMesh for a data warehousing project on Databricks Unity Catalog, as an alternative to dbt.

SQLMesh is very promising. I especially like:
- Can run it easily from a notebook.
- Lots of built-in audits.
- Minimal YAML.
- Halting audits to prevent downstream corruption.

One issue I have though is that the "access" environment / schema uses views on the tables in the physical layer. The problem here is that with Unity Catalog I would need to grant users access to the physical schema to allow them to select from the views. I would like to avoid this, because my users will be confused by i, and I would like to avoid endless "don't use these tables in the sqlmesh___ schema" conversations. 

Would be possible to add an option to use shallow clones of the physical tables rather than views?

https://docs.databricks.com/en/delta/clone-unity-catalog.html

```
create or replace table sqlmesh_example.full_model_shallow 
 shallow clone sqlmesh__sqlmesh_example.sqlmesh_example__full_model__2360225307;
```

Permissions on the shallow clones can be granted independently if you are using shared access mode compute. This way, we could grant permissions to the "access" schema and avoid exposing the physical schema.

On problem I can see with the shallow clone idea is that cloned tables reflect the data of the source table at the time of the clone operation. Changes in the source table are not reflected in the clone. A `create or replace table` statement is required refresh the clone.

Cheers, Pat

**Comment by eakmanrq** [comment]
Thanks for the thorough feedback Pat!

> On problem I can see with the shallow clone idea is that cloned tables reflect the data of the source table at the time of the clone operation. Changes in the source table are not reflected in the clone. A create or replace table statement is required refresh the clone.

Yeah this is the main issue with this proposal. Currently are virtual environments have a characteristic to them that if your have a table you did not change then the view your environment will represent exactly what is in production currently. This makes previewing/validating changes much more powerful since you are seeing exactly what production will be before deploying. If we start cloning then this characteristic goes away and users will have stale representations of their data when they go to preview/validate a change. 

I understand your reasoning for wanting this change though. Do you happen to know if Databricks allows granting permissions between schemas? Some engines allow you to do something like this:

`Schema A` has a view that reads from a table in `Schema B`
* Grant `Select` Access to `User` on `Schema A`
* Grant `Select` Access on `Schema B` to `Schema A` <- key change

Now `User` only have `select` access to `Schema A` but is allowed to read from `Schema B` if views exist in `Schema A` that access `Schema B`. If it allows this pattern then I believe that would solve your issue.

**Comment by PtrckGdwn** [comment]
Hi

Unfortunately, Unity Catalog does not have this ability - you have to grant use catalog, use schema, and select on the schema in which the view's base table is located. I had hoped for something along the lines of what you describe but it's a no go. 

Thanks, Pat

**Comment by eakmanrq** [comment]
Well that is unfortunate. Databricks did just recently rollout the Unity so it is possible that we will see this added. Until then it does sound like they will need read access to the physical schema then. 

We do offer a way to override the prefix of a physical schema created on a per-schema basis. Therefore if the concern is around confusing users then you could consider having a prefix that better communicates not to interact directly with the tables (`private`, `internal`, `zzz`, ect.). 

https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#physical-table-schemas

Also keep in mind the tables produced in the physical schema all have their hashes assigned to them and generally not look very "user facing" to begin with. That, potentially combined with a new prefix, could minimize potential for confusion.

**Comment by PtrckGdwn** [comment]
No worries! 

Thanks for the prompt responses too, very much appreciated.
