### ISSUE TITLE
Allow for environment name in uppercase

### ISSUE THREAD

**Issue by plamen-ivanov-avios** [TobikoData/sqlmesh#1978]
At the moment environment names are always converted to lowercase even if I set them as STG or 'STG'.
Could you please allow for uppercase names?
This way it will be easier to comply with company's naming convention.

**Comment by eakmanrq** [comment]
@plamen-ivanov-avios Thanks for making this issue. So far we have been able to avoid the extra complexity that goes along with support case-sensitive environment names/symbols in environment names since this hasn't been requested. So I don't see us supporting this in the near term. If more users have a need for this feature though that will help increase the prioritization of it.

**Comment by eakmanrq** [comment]
Going to close this issue since we don't plan on addressing anytime soon. Others can upvote or provide your own additional context for it if you would also benefit from this.
