### ISSUE TITLE
`sqlmesh format` placement of column comments is inconsistent

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#1982]
Given this input model:

```sql
MODEL(name foo, kind VIEW);
SELECT
  -- 1
  column_a,
  -- 2
  column_a AS b,
  -- 3
  column_a + 1 AS c,
FROM
  bar

```

Running `sqlmesh format` results in this:

```sql
MODEL (
  name foo,
  kind VIEW
);

SELECT
  column_a, /* 1 */
  column_a /* 2 */ AS b,
  column_a /* 3 */ + 1 AS c
FROM bar
```

Presumably, it should have placed all comments after the full declaration (after the comma).

**Comment by georgesittas** [comment]
Hey @plaflamme, I've addressed the second case in https://github.com/tobymao/sqlglot/pull/2853, but the third one is not simple to fix because the sqlglot tokenizer attaches `3` to `column_a` in both of the following queries:

```sql
SELECT
  -- 3
  column_a + 1 AS c;

SELECT
  column_a /* 3 */ + 1 AS c;
```

One could argue that we can bubble up the comment and attach it to the alias like I did in that PR, but then that could mess up other cases were the comments are intentionally placed next to the column and we don't want them next to the alias.

There may be a path to fix this by introducing more metadata for the comments (e.g. line / col numbers) and updating the comment-attaching logic in the AST, but that's not really in scope so I'll mark this issue as not planned for the time being.
