### ISSUE TITLE
Connect to multiple databases

### ISSUE THREAD

**Issue by gunar** [TobikoData/sqlmesh#2252]
Is it possible to connect SQLMesh to multiple database?

I'm trying to use SQLMesh to Extract data from DB1, Transform it, then Store it in DB2.

```
DB1 => SQLMesh => DB2
```

I've read the documentation on `EXTERNAL` models and on Gateway, but I don't see how it's possible. So I though I might ask because it seems like I'm missing something about how to think about SQLMesh.

If I understand correctly now, SQLMesh connects to only one database at the time. And `EXTERNAL` models are not external in that they connect to a different database server. They're table in the same database server, they're just tables not created by SQLMesh itself.

Did I get it right?

**Comment by tobymao** [comment]
Right now, the only way to do this is to use a Python Model for DB1, transform it there, and then upload it to DB2.

So for example in DB1, you write a Python model...

```python
# db1.py

import duckdb

from sqlmesh import model
from sqlmesh.core.model import FullKind

@model(
    "bgdb.collection",
    description="All of the board games in my personal collection.",
    kind=FullKind(),
    columns={
        "id": "int",
        "name": "text",
        "rating": "float",
        "plays": "int",
        "min_players": "int",
        "max_players": "int",
        "rec_num_players": "text",
        "best_num_players": "text",
        "year_published": "int",
        "play_rank": "int",
    },
)
def execute(context, start, end, execution_time, **kwargs):
    conn = duckdb.connect()

    conn.execute("""
    SELECT
      objectid AS id,
      objectname AS name,
      rating,
      COALESCE(numplays, 0) AS plays,
      minplayers AS min_players,
      maxplayers AS max_players,
      bggrecplayers AS rec_num_players,
      bggbestplayers AS best_num_players,
      yearpublished AS year_published,
      DENSE_RANK() OVER(ORDER BY plays desc) AS play_rank
    FROM READ_CSV('seeds/collection.csv')
    """)

    return conn.fetchdf()
```

You can do anything you want here, API calls, as long as you return a DataFrame. SQLMesh will automatically upload this dataset to DB2. The downside here is that this needs be fit on your machine, but it's sort of inevitable because unless DB1 and DB2 can actually talk to each other, you need some way to transport the data.

If DB1 and DB2 share the same metastore + storage layer, it could be possible to support this in the future. For example if you use Presto + Spark on Hive stored in S3. However, this is not supported today.
