### ISSUE TITLE
Adding external model definitions trigger planning

### ISSUE THREAD

**Issue by MikeWallis42** [TobikoData/sqlmesh#2871]
Before running `sqlmesh create_external_models` there's nothing to report in my plan but afterwards it seems to be forcing a complete re-build of the estate.
Is this expected behaviour? I would have expected that adding column metadata for lineage purposes would not have caused this.

I'm running the very latest version 0.109.2

**Comment by izeigerman** [comment]
@MikeWallis42 yes, adding external models may result in SQLMesh detecting breaking changes for models referencing them. This could be due to several factors:

1. If you use `SELECT *` in some of the impacted models. Now that the external models are available, SQLMesh expands the `*` into actual columns and versions them accordingly. 
2. You don't use `SELECT *` but you don't specify projection types either. With type information available, SQLMesh propagates those types across all downstream models and versions them accordingly. 

In either case if you want to avoid backfilling everything, you can run the plan command with the `--forward-only` flag this one time after adding external models. This will result in all changes being categorized as `Forward-only` (applied going "forward"), which would avoid the backfill altogether.

Please feel free to re-open the issue if you have any follow-up questions.

**Comment by MikeWallis42** [comment]
Thank you for getting back to me @izeigerman, I believe I fell in to option 2, thank you for giving me a way to ignore this type of change.
