### ISSUE TITLE
Support macros in pre/post statements

### ISSUE THREAD

**Issue by MikeWallis42** [TobikoData/sqlmesh#2886]
I would like to be able to run a post statement after my modelling to do things like Iceberg housekeeping type activities (optimise, expire snapshots, remove orphan files) on the current model.
Would it be possible to support the use of macros like @VAR / @this like with audits for pre and post statements?

**Comment by georgesittas** [comment]
I think `@var(...)` should be supported, and instead of `this` you can generally just use the model name and it will be resolved into the name of the underlying materialized table for that model.

One exception here is when the pre/post-statement fails to be parsed by SQLGlot. When that happens, you need to use the Jinja syntax, i.e. `{{ this_model }}`. Don't forget to wrap the relevant statement(s) in `JINJA_STATEMENT_BEGIN;` and `JINJA_STATEMENT_END;`.

If you do come across such examples feel free to file tickets and we'll take a look. These surface as either `ParseErrors` where the execution halts, or as warnings that look like _"[...] falling back into Command"_.

I'll close this for now as there's no clear action item, but happy to continue discussing and reopen if you encounter any issues.

**Comment by MikeWallis42** [comment]
Legend! This worked 😄

```
JINJA_STATEMENT_BEGIN;
ALTER TABLE {{ this_model }} EXECUTE optimize
JINJA_END;
```

For the record `@var` doesn't seem to work and the reason it was an issue for me is because I'm developing "dbt style" with a separate schema per user, purely so we don't step on each others toes for now as we're building from scratch.
