### ISSUE TITLE
Switch user configuration without triggering Model changes.

### ISSUE THREAD

**Issue by hustic** [TobikoData/sqlmesh#2941]
I am using SQLMesh for both Extraction and Modelling.
I have a few Python Models for Extraction that use Environment Variables to load Credentials for API requests.
I want to share the SQLMesh project repo with members of my team that do not have access to those Credentials. 

My thinking was that I could define them in `config` with a default value and then overload them during production runs or when an engineer wants to debug the extractors. However, SQLMesh will detect that there is a difference between the default and overloaded versions and `plan` will pick up the Python models that use them.

What is the proper to do this?

What I tried so far that did not work:
- Accessing the EnvVars from the Python task itself.
- Defining them as `variables` and override them with other EnvVars
- Use `--select-model` to filter but that lead to #2936

**Comment by eakmanrq** [comment]
> I want to share the SQLMesh project repo with members of my team that do not have access to those Credentials.

So if running SQLMesh with Built-in scheduler then it was designed as a way of sharing secrets like this across team members who wouldn't otherwise have access. If people are going to be running plan/apply (or run) directly from their computer then they need their environments configured to have the proper access to do so. 

Therefore in your Python models you would us something like `os.environ` to get the required environment variables to access the API you are mentioning. This would result in no changes in model when the value changes since the model definition would be static (just a call to `os.environ`). 

If you are wanting users to not have an access, and therefore want them to defer execution to something else that does have access, you can use the Airflow integration or the Tobiko Cloud offering is planned to also offer this functionality.

**Comment by hustic** [comment]
Thanks for the response! 
I'm commenting to share the solution:

The environment variables need to be accessed inside the `execute` method for the model definition to remain static when the variables change.
