### ISSUE TITLE
`sqlmesh table_diff` on `BigQuery` gateway is unable to compare `ARRAY`

### ISSUE THREAD

**Issue by camilleAmaury** [TobikoData/sqlmesh#3411]
Hi everyone,

I faced an issue on `BigQuery` using the `sqlmesh table_diff` command. It seems that is not possible to compare Arrays.

Here is a reproductible example :
`version : 0.135.1`
[bigquery_reproductible_models_and_tests.zip](https://github.com/user-attachments/files/17869153/bigquery_reproductible_models_and_tests.zip)

You can find the models in the `models/` folder, and the commands in the `test/` folder.
I defined 3 models with string array :
* `x000_str_array` compared to `x002_str_array_3` => should be `100%`
* `x000_str_array`compared to `x001_str_array_2` => should be `0%`

I defined 3 models with struct array :
* `x100_struct_array` compared to `x102_struct_array_3` => should be `100%`
* `x100_struct_array` compared to `x101_struct_array_2` => should be `0%`

Currently, while executing the commands, I face these errors : 
```
google.api_core.exceptions.BadRequest: 400 Equality is not defined for arguments of type ARRAY<STRING> at [1:1052]; reason: invalidQuery, location: query, message: Equality is not defined for arguments of type ARRAY<STRING> at [1:1052]
```
```
google.api_core.exceptions.BadRequest: 400 Equality is not defined for arguments of type ARRAY<STRUCT<struct_id INT64, struct_value STRING>> at [1:1076]; reason: invalidQuery, location: query, message: Equality is not defined for arguments of type ARRAY<STRUCT<struct_id INT64, struct_value STRING>> at [1:1076]
```

Is there any workaround ?

**Comment by erindru** [comment]
Hi there. Firstly, thanks so much for providing test cases!

Currently we just [rely on](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/table_diff.py#L293) the database engine's `=` operator when testing for value equality and it appears this doesn't work on BigQuery for ARRAY and STRUCT types.

This can definitely be improved but in the meantime, as a workaround, you could try converting those types to some kind of string representation (eg wrapping the columns being compared in `to_json_string()`) and comparing that instead

**Comment by esciara** [comment]
Actually, it seems a bit tricky: [`TO_JSON_STRING`](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#to_json_string) produces a string, which means that 2 equivalent jsons with keys appearing in different orders would be flagged as different...

And [`TO_JSON`](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#to_json) would not work since the [`JSON` type does not support equality](https://cloud.google.com/bigquery/docs/json-data#create_a_table_with_a_json_column)...

Another route to explore might be [using `UNNEST`](https://stackoverflow.com/a/43671119/4374048)? But then complex objects containing encapsulated `STRUCT` and `ARRAY` would not work either...

**Comment by esciara** [comment]
I guess that if they are ordered and one wants the records to be equal, then it would be the responsibility of the developer to make sure that the arrays and structs are actually in the same order on both tables. So an equality test on a `TO_JSON_STRING` would be completely reasonable... wouldn't it?

**Comment by erindru** [comment]
I think so, that's why I suggested it as a workaround in the short term.

Our actual solution might look similar, we are still discussing internally the best way to implement this

**Comment by esciara** [comment]
🙏
