### ISSUE TITLE
create model option and defaults to not optimize

### ISSUE THREAD

**Issue by tobymao** [TobikoData/sqlmesh#3479]
optimizing takes time and can increase sql payload size.

make a model option to control the level of optimization per model and at a project level.

cc @VaggelisD

**Comment by esciara** [comment]
Hi.

Could you explain or point to the definition (doc?) of "optimize" that is used here?

I am asking because as this optimization is certainly [not for size of the sql](https://github.com/TobikoData/sqlmesh/issues/3472#issuecomment-2521799118), nor for speed as I could observe that it could take quite a while to generate the "optimized" sql.

Thx

**Comment by georgesittas** [comment]
> Hi.
> 
> Could you explain or point to the definition (doc?) of "optimize" that is used here?
> 
> I am asking because as this optimization is certainly [not for size of the sql](https://github.com/TobikoData/sqlmesh/issues/3472#issuecomment-2521799118), nor for speed as I could observe that it could take quite a while to generate the "optimized" sql.
> 
> Thx

There are some transformations applied to the query that simplify it, e.g. by folding constants. These transformations are part of [SQLGlot's optimizer](https://github.com/tobymao/sqlglot/tree/main/sqlglot/optimizer), hence the term.

**Comment by izeigerman** [comment]
I don't think the default should be not optimziing

**Comment by georgesittas** [comment]
Yep, I don't think it is, @VaggelisD made it so that it's only opt-out by setting the flag (or model default) to false.
