### ISSUE TITLE
SQLMesh doesn't communicate impact on downstream models if a model is renamed

### ISSUE THREAD

**Issue by foundinblank** [TobikoData/sqlmesh#706]
I think this can be repro by: 

1. In the example project, run `sql plan` 
2. In `example_incremental_model.sql` rename `name` to `sqlmesh_example.example_incremental_model_renamed` 
3. Re-run `sql plan` 

The output is this: 
```
Summary of differences against `prod`:
├── Added Models:
│   └── sqlmesh_example.example_incremental_model_renamed
├── Removed Models:
│   └── sqlmesh_example.example_incremental_model
└── Indirectly Modified:
    └── sqlmesh_example.example_full_model
```

The dag is `incremental -> full` so renaming `incremental_model` breaks the dag. But because `sqlmesh_example.example_full_model` isn't rebuilt, there is no error thrown (even though there should be; the full model now has a broken upstream reference)

**Comment by tobymao** [comment]
did you choose non-breaking? renaming a mode like this is a breaking change.

**Comment by foundinblank** [comment]
What do you mean by "choose non-breaking?" Where in the app do I make that choice?

**Comment by foundinblank** [comment]
I think I'm in auto mode.

**Comment by izeigerman** [comment]
@foundinblank thanks a lot for discovering this!

The reason execution fails is because even though the model with the old name was technically dropped, its name still resolves into a valid reference since the version of this removed model is till promoted on production. This happens because we backfill models before we update views for the target environment. Once you apply the change in prod, the subsequent evaluation of the `full` model will fail since the view name will have been removed at that point.

After some discussion we think that the best way forward would be checking whether a model that is about to be removed has any downstream references and fail if it does at the plan creation time. The only edge case we could think of where this approach fails is when a user decides to manage that table / view outside SQLMesh. But in that case it will have to be first demoted in production environment anyway.

Please let us know if you see any concerns with the suggested solution.

**Comment by foundinblank** [comment]
I think that sounds good!
